### ISSUE TITLE
App Feature 5: Finish building the entire (basic) user interface

### ISSUE THREAD

**Issue by thatgirldorian** [chingu-voyages/v38-toucans-team-02#18]
**__Task Description__**

- [ ] Build out the first web app page
- [ ] Finish building out the sidebar
- [ ] Work on the UI for today's weather and the next couple of days
- [ ] Build the UI for Today's Highlights
- [ ] Make the user interface responsive
